### ISSUE TITLE
--eslint-active-p not compatible with lsp-mode

### ISSUE THREAD

**Issue by orzechowskid** [DamienCassou/eslint-disable-rule#6]
`eslint-disable-rule` works great for me when working with individual files but does not seem to work for me when using `lsp-mode`.  this minor mode by default will set `flycheck-enabled-checkers` to `'(lsp)` meaning `eslint-disable-rule-flycheck--eslint-active-p` will return `nil`.  (it's possible to configure `lsp-mode` to use alternate checkers such as flymake, and I wonder if the same problem will occur with `eslint-disable-rule--flymake-eslint-active-p`.)

I was about to open a small PR to patch that function, basically like this:
```diff
+ (and (featurep 'lsp) lsp-diagnostics-mode (eq lsp-diagnostics-provider :flycheck))
```

but then I was wondering why you need to look for the checker at all.  is the `'flycheck-error` text property not sufficient?

regardless, thanks for your work on this library :)

**Comment by DamienCassou** [comment]
I'm ok for a PR removing `(member 'javascript-eslint flycheck-enabled-checkers)` from `eslint-disable-rule-flycheck--eslint-active-p`.

**Comment by justinbarclay** [comment]
An alternative could be:
```
(and (featurep 'lsp-eslint) (lsp-find-workspace 'eslint (buffer-file-name))
```
This would avoid the flycheck vs flymake problem and just see if lsp-eslint is running in the current buffer.

**Comment by DamienCassou** [comment]
Can one of you please send a PR?
